name: Agregar comunidad
description: Proponer una nueva comunidad tech para el directorio
title: "[Comunidad] "
labels: ["comunidad"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por querer agregar una comunidad a peruanos.dev! 
        Por favor completa la siguiente informaci贸n.

  - type: input
    id: name
    attributes:
      label: Nombre de la comunidad
      description: Nombre oficial de la comunidad
      placeholder: "ej. React Peru"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: Describe brevemente la comunidad (prop贸sito, actividades, etc.)
      placeholder: |
        Somos una comunidad que...
    validations:
      required: true

  - type: input
    id: logo_url
    attributes:
      label: URL del logo
      description: Link al logo de la comunidad (preferiblemente PNG o SVG)
      placeholder: "https://ejemplo.com/logo.png"
    validations:
      required: true

  - type: input
    id: city
    attributes:
      label: Ciudad
      description: Ciudad principal donde opera la comunidad
      placeholder: "ej. Lima"
    validations:
      required: true

  - type: input
    id: topics
    attributes:
      label: Temas/Topics
      description: Temas principales separados por comas
      placeholder: "react, javascript, frontend, web"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "##  Informaci贸n de Contacto"

  - type: input
    id: email
    attributes:
      label: Email
      description: Email de contacto de la comunidad
      placeholder: "contacto@ejemplo.com"
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Website
      description: URL del sitio web oficial (o red social principal si no tienen)
      placeholder: "https://reactperu.org"
    validations:
      required: true

  - type: input
    id: github
    attributes:
      label: GitHub
      description: (Opcional) URL del perfil o organizaci贸n en GitHub
      placeholder: "https://github.com/reactperu"

  - type: input
    id: twitter
    attributes:
      label: Twitter/X
      description: (Opcional) URL del perfil en Twitter/X
      placeholder: "https://twitter.com/reactperu"

  - type: input
    id: linkedin
    attributes:
      label: LinkedIn
      description: (Opcional) URL de la p谩gina en LinkedIn
      placeholder: "https://linkedin.com/company/reactperu"

  - type: input
    id: discord
    attributes:
      label: Discord
      description: (Opcional) URL del servidor de Discord
      placeholder: "https://discord.gg/..."

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmaci贸n
      description: Por favor confirma lo siguiente
      options:
        - label: He verificado que la comunidad no est茅 duplicada
          required: true
        - label: El logo es de buena calidad y tiene formato SVG o PNG
          required: true
        - label: La informaci贸n proporcionada es correcta
          required: true
        - label: Represento a esta comunidad o tengo permiso para agregarla
          required: true
