name:  Agregar Proyecto Open Source
description: Proponer un proyecto de c贸digo abierto creado por peruanos
title: "[Proyecto] "
labels: ["proyecto", "open-source"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por querer agregar un proyecto a peruanos.dev! 
        Por favor completa la siguiente informaci贸n.

  - type: input
    id: owner
    attributes:
      label: Owner (Usuario o Organizaci贸n de GitHub)
      description: Nombre del usuario u organizaci贸n propietaria del repositorio
      placeholder: "ej. username o organization-name"
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: Nombre del repositorio
      description: Nombre del repositorio en GitHub
      placeholder: "ej. awesome-project"
    validations:
      required: true

  - type: input
    id: full_url
    attributes:
      label: URL completa del repositorio
      description: Para verificaci贸n
      placeholder: "https://github.com/username/awesome-project"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: 驴Por qu茅 deber铆a incluirse este proyecto?
      description: Explica brevemente por qu茅 este proyecto es relevante para la comunidad
      placeholder: |
        Este proyecto es relevante porque...
    validations:
      required: true

  - type: input
    id: technologies
    attributes:
      label: Tecnolog铆as principales
      description: Lenguajes de programaci贸n o frameworks principales
      placeholder: "ej. TypeScript, React, Node.js"

  - type: checkboxes
    id: requirements
    attributes:
      label: Requisitos del proyecto
      description: Verifica que el proyecto cumpla con lo siguiente
      options:
        - label: El proyecto es de c贸digo abierto (open source)
          required: true
        - label: El repositorio es p煤blico en GitHub
          required: true
        - label: El proyecto est谩 creado o mantenido por desarrolladores peruanos
          required: true
        - label: El proyecto tiene un README.md descriptivo
          required: true
        - label: El proyecto tiene actividad reciente o es relevante para la comunidad
          required: true
        - label: El proyecto no est谩 duplicado en la lista actual
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        **Nota:** La informaci贸n detallada del proyecto (descripci贸n, estrellas, lenguaje, etc.) 
        se obtendr谩 autom谩ticamente de la API de GitHub.
